### ISSUE TITLE
Url voor zoeken van een product

### ISSUE THREAD

**Issue by fredpeertje** [RinseV/plus-wrapper#1]
Hi Rinse,
Is er ergens een documentatie beschikbaar voor deze API? Bijvoorbeeld een Swagger pagina? Of heb je alle info zelf gevonden via data scraping uit de Mobile App?

Ik ben benieuwd wat de URL is om alle producten te krijgen met het woord banaan erin. Zou je mij kunnen vertellen wat de URL hiervan is?

Ik had zelf een van deze verwacht
`https://pls-sprmrkt-mw.prd.vdc1.plus.nl/api/v3/navigation-search?q=banaan
https://pls-sprmrkt-mw.prd.vdc1.plus.nl/api/v3/product/navigation-search?q=banaan
`

**Comment by RinseV** [comment]
Alle endpoints van de API zijn gescraped vanuit de mobile app, ik heb dus geen idee welke endpoints er allemaal bestaan. Je zou zelf kunnen proberen om de app te scrapen, maar dit is niet héél voor de hand liggend. Er zijn wel [enkele tutorials](https://approov.io/blog/how-to-mitm-attack-the-api-of-an-android-app) online te vinden over hoe je de API van een (Android) app kan scrapen, maar ik weet zelf niet in hoeverre deze stappen te volgen zijn voor wat "grotere" apps zoals die van de Plus (of elke andere willekeurige supermarkt). Weet wel dat je voor de meeste van deze apps ook root nodig hebt zodat je een [SSL-Unpinning](https://modules.lsposed.org/module/io.github.tehcneko.sslunpinning) module kan installeren op iets van XPosed/LSPosed.

Vanuit de [`product().getProductsFromName()` functie](https://github.com/RinseV/plus-wrapper/blob/main/src/product/product.ts#L44) kan je ook het endpoint zien. Voor de query `banaan` kom je uit op `https://pls-sprmrkt-mw.prd.vdc1.plus.nl/api/v3/navigation-search?tn_q=banaan`.

**Comment by fredpeertje** [comment]
@RinseV bedankt voor de duidelijke uitleg! :D 

Ah het is dus `tn_q` ipv `q`
